### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by szubartm**

### CODE REVIEW

**Comment by MichalBrylka** [comment]
@szubartm Could you please squash your changes:
`git rebase -i HEAD~4`
?

More info:
[Squash](https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history)

**Comment by MichalBrylka** [comment]
other than that, it looks ok when I look at rendered version at your branch:
https://github.com/szubartm/AdhocLinq#_Dynamic_Expression_API

happy to approve this change after squash

**Comment by szubartm** [comment]
> @szubartm Could you please squash your changes: `git rebase -i HEAD~4` ?
> 
> More info: [Squash](https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history)

Sure, should be ok now.

**Comment by MichalBrylka** [comment]
Approved. THX

**Pull request merged**
